[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "5SH9yDLw4o7BfhXHPbnepiuHWf8fvygcrhnPmMByxBm1"

[programs.devnet]
counter = "5SH9yDLw4o7BfhXHPbnepiuHWf8fvygcrhnPmMByxBm1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
